/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LangUnauthImport } from './routes/$lang/_unauth'
import { Route as LangAuthImport } from './routes/$lang/_auth'
import { Route as LangUnauthIndexImport } from './routes/$lang/_unauth/index'
import { Route as LangUnauthLoginImport } from './routes/$lang/_unauth/login'
import { Route as LangAuthAnotherImport } from './routes/$lang/_auth/another'
import { Route as LangAuthDashboardInvoicesLayoutImport } from './routes/$lang/_auth/dashboard/invoices/_layout'
import { Route as LangAuthDashboardContentLayoutImport } from './routes/$lang/_auth/dashboard/content/_layout'
import { Route as LangAuthDashboardInvoicesLayoutIndexImport } from './routes/$lang/_auth/dashboard/invoices/_layout/index'
import { Route as LangAuthDashboardContentLayoutIndexImport } from './routes/$lang/_auth/dashboard/content/_layout/index'
import { Route as LangAuthDashboardContentLayoutUsersImport } from './routes/$lang/_auth/dashboard/content/_layout/users'
import { Route as LangAuthDashboardContentLayoutCommentsImport } from './routes/$lang/_auth/dashboard/content/_layout/comments'
import { Route as LangAuthDashboardContentLayoutPostsIndexImport } from './routes/$lang/_auth/dashboard/content/_layout/posts/index'
import { Route as LangAuthDashboardInvoicesLayoutInvoiceIdImport } from './routes/$lang/_auth/dashboard/invoices/_layout/_.$invoiceId'
import { Route as LangAuthDashboardContentLayoutPostsLayoutImport } from './routes/$lang/_auth/dashboard/content/_layout/posts/_layout'
import { Route as LangAuthDashboardContentLayoutPostsLayoutPostIdImport } from './routes/$lang/_auth/dashboard/content/_layout/posts/_layout.$postId'

// Create Virtual Routes

const LangImport = createFileRoute('/$lang')()
const LangAuthDashboardInvoicesImport = createFileRoute(
  '/$lang/_auth/dashboard/invoices',
)()
const LangAuthDashboardContentImport = createFileRoute(
  '/$lang/_auth/dashboard/content',
)()
const LangAuthDashboardContentLayoutPostsImport = createFileRoute(
  '/$lang/_auth/dashboard/content/_layout/posts',
)()

// Create/Update Routes

const LangRoute = LangImport.update({
  path: '/$lang',
  getParentRoute: () => rootRoute,
} as any)

const LangUnauthRoute = LangUnauthImport.update({
  id: '/_unauth',
  getParentRoute: () => LangRoute,
} as any)

const LangAuthRoute = LangAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LangRoute,
} as any)

const LangUnauthIndexRoute = LangUnauthIndexImport.update({
  path: '/',
  getParentRoute: () => LangUnauthRoute,
} as any)

const LangUnauthLoginRoute = LangUnauthLoginImport.update({
  path: '/login',
  getParentRoute: () => LangUnauthRoute,
} as any)

const LangAuthAnotherRoute = LangAuthAnotherImport.update({
  path: '/another',
  getParentRoute: () => LangAuthRoute,
} as any)

const LangAuthDashboardInvoicesRoute = LangAuthDashboardInvoicesImport.update({
  path: '/dashboard/invoices',
  getParentRoute: () => LangAuthRoute,
} as any)

const LangAuthDashboardContentRoute = LangAuthDashboardContentImport.update({
  path: '/dashboard/content',
  getParentRoute: () => LangAuthRoute,
} as any)

const LangAuthDashboardInvoicesLayoutRoute =
  LangAuthDashboardInvoicesLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LangAuthDashboardInvoicesRoute,
  } as any)

const LangAuthDashboardContentLayoutRoute =
  LangAuthDashboardContentLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LangAuthDashboardContentRoute,
  } as any)

const LangAuthDashboardContentLayoutPostsRoute =
  LangAuthDashboardContentLayoutPostsImport.update({
    path: '/posts',
    getParentRoute: () => LangAuthDashboardContentLayoutRoute,
  } as any)

const LangAuthDashboardInvoicesLayoutIndexRoute =
  LangAuthDashboardInvoicesLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LangAuthDashboardInvoicesLayoutRoute,
  } as any)

const LangAuthDashboardContentLayoutIndexRoute =
  LangAuthDashboardContentLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LangAuthDashboardContentLayoutRoute,
  } as any)

const LangAuthDashboardContentLayoutUsersRoute =
  LangAuthDashboardContentLayoutUsersImport.update({
    path: '/users',
    getParentRoute: () => LangAuthDashboardContentLayoutRoute,
  } as any)

const LangAuthDashboardContentLayoutCommentsRoute =
  LangAuthDashboardContentLayoutCommentsImport.update({
    path: '/comments',
    getParentRoute: () => LangAuthDashboardContentLayoutRoute,
  } as any)

const LangAuthDashboardContentLayoutPostsIndexRoute =
  LangAuthDashboardContentLayoutPostsIndexImport.update({
    path: '/',
    getParentRoute: () => LangAuthDashboardContentLayoutPostsRoute,
  } as any)

const LangAuthDashboardInvoicesLayoutInvoiceIdRoute =
  LangAuthDashboardInvoicesLayoutInvoiceIdImport.update({
    path: '/$invoiceId',
    getParentRoute: () => LangAuthDashboardInvoicesLayoutRoute,
  } as any)

const LangAuthDashboardContentLayoutPostsLayoutRoute =
  LangAuthDashboardContentLayoutPostsLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LangAuthDashboardContentLayoutPostsRoute,
  } as any)

const LangAuthDashboardContentLayoutPostsLayoutPostIdRoute =
  LangAuthDashboardContentLayoutPostsLayoutPostIdImport.update({
    path: '/$postId',
    getParentRoute: () => LangAuthDashboardContentLayoutPostsLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangImport
      parentRoute: typeof rootRoute
    }
    '/$lang/_auth': {
      id: '/$lang/_auth'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_unauth': {
      id: '/$lang/_unauth'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangUnauthImport
      parentRoute: typeof LangImport
    }
    '/$lang/_auth/another': {
      id: '/$lang/_auth/another'
      path: '/another'
      fullPath: '/$lang/another'
      preLoaderRoute: typeof LangAuthAnotherImport
      parentRoute: typeof LangAuthImport
    }
    '/$lang/_unauth/login': {
      id: '/$lang/_unauth/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangUnauthLoginImport
      parentRoute: typeof LangUnauthImport
    }
    '/$lang/_unauth/': {
      id: '/$lang/_unauth/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangUnauthIndexImport
      parentRoute: typeof LangUnauthImport
    }
    '/$lang/_auth/dashboard/content': {
      id: '/$lang/_auth/dashboard/content'
      path: '/dashboard/content'
      fullPath: '/$lang/dashboard/content'
      preLoaderRoute: typeof LangAuthDashboardContentImport
      parentRoute: typeof LangAuthImport
    }
    '/$lang/_auth/dashboard/content/_layout': {
      id: '/$lang/_auth/dashboard/content/_layout'
      path: '/dashboard/content'
      fullPath: '/$lang/dashboard/content'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutImport
      parentRoute: typeof LangAuthDashboardContentRoute
    }
    '/$lang/_auth/dashboard/invoices': {
      id: '/$lang/_auth/dashboard/invoices'
      path: '/dashboard/invoices'
      fullPath: '/$lang/dashboard/invoices'
      preLoaderRoute: typeof LangAuthDashboardInvoicesImport
      parentRoute: typeof LangAuthImport
    }
    '/$lang/_auth/dashboard/invoices/_layout': {
      id: '/$lang/_auth/dashboard/invoices/_layout'
      path: '/dashboard/invoices'
      fullPath: '/$lang/dashboard/invoices'
      preLoaderRoute: typeof LangAuthDashboardInvoicesLayoutImport
      parentRoute: typeof LangAuthDashboardInvoicesRoute
    }
    '/$lang/_auth/dashboard/content/_layout/comments': {
      id: '/$lang/_auth/dashboard/content/_layout/comments'
      path: '/comments'
      fullPath: '/$lang/dashboard/content/comments'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutCommentsImport
      parentRoute: typeof LangAuthDashboardContentLayoutImport
    }
    '/$lang/_auth/dashboard/content/_layout/users': {
      id: '/$lang/_auth/dashboard/content/_layout/users'
      path: '/users'
      fullPath: '/$lang/dashboard/content/users'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutUsersImport
      parentRoute: typeof LangAuthDashboardContentLayoutImport
    }
    '/$lang/_auth/dashboard/content/_layout/': {
      id: '/$lang/_auth/dashboard/content/_layout/'
      path: '/'
      fullPath: '/$lang/dashboard/content/'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutIndexImport
      parentRoute: typeof LangAuthDashboardContentLayoutImport
    }
    '/$lang/_auth/dashboard/invoices/_layout/': {
      id: '/$lang/_auth/dashboard/invoices/_layout/'
      path: '/'
      fullPath: '/$lang/dashboard/invoices/'
      preLoaderRoute: typeof LangAuthDashboardInvoicesLayoutIndexImport
      parentRoute: typeof LangAuthDashboardInvoicesLayoutImport
    }
    '/$lang/_auth/dashboard/content/_layout/posts': {
      id: '/$lang/_auth/dashboard/content/_layout/posts'
      path: '/posts'
      fullPath: '/$lang/dashboard/content/posts'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutPostsImport
      parentRoute: typeof LangAuthDashboardContentLayoutImport
    }
    '/$lang/_auth/dashboard/content/_layout/posts/_layout': {
      id: '/$lang/_auth/dashboard/content/_layout/posts/_layout'
      path: '/posts'
      fullPath: '/$lang/dashboard/content/posts'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutPostsLayoutImport
      parentRoute: typeof LangAuthDashboardContentLayoutPostsRoute
    }
    '/$lang/_auth/dashboard/invoices/_layout//$invoiceId': {
      id: '/$lang/_auth/dashboard/invoices/_layout//$invoiceId'
      path: '/$invoiceId'
      fullPath: '/$lang/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof LangAuthDashboardInvoicesLayoutInvoiceIdImport
      parentRoute: typeof LangAuthDashboardInvoicesLayoutImport
    }
    '/$lang/_auth/dashboard/content/_layout/posts/': {
      id: '/$lang/_auth/dashboard/content/_layout/posts/'
      path: '/'
      fullPath: '/$lang/dashboard/content/posts/'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutPostsIndexImport
      parentRoute: typeof LangAuthDashboardContentLayoutPostsImport
    }
    '/$lang/_auth/dashboard/content/_layout/posts/_layout/$postId': {
      id: '/$lang/_auth/dashboard/content/_layout/posts/_layout/$postId'
      path: '/$postId'
      fullPath: '/$lang/dashboard/content/posts/$postId'
      preLoaderRoute: typeof LangAuthDashboardContentLayoutPostsLayoutPostIdImport
      parentRoute: typeof LangAuthDashboardContentLayoutPostsLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LangRoute: LangRoute.addChildren({
    LangAuthRoute: LangAuthRoute.addChildren({
      LangAuthAnotherRoute,
      LangAuthDashboardContentRoute: LangAuthDashboardContentRoute.addChildren({
        LangAuthDashboardContentLayoutRoute:
          LangAuthDashboardContentLayoutRoute.addChildren({
            LangAuthDashboardContentLayoutCommentsRoute,
            LangAuthDashboardContentLayoutUsersRoute,
            LangAuthDashboardContentLayoutIndexRoute,
            LangAuthDashboardContentLayoutPostsRoute:
              LangAuthDashboardContentLayoutPostsRoute.addChildren({
                LangAuthDashboardContentLayoutPostsLayoutRoute:
                  LangAuthDashboardContentLayoutPostsLayoutRoute.addChildren({
                    LangAuthDashboardContentLayoutPostsLayoutPostIdRoute,
                  }),
                LangAuthDashboardContentLayoutPostsIndexRoute,
              }),
          }),
      }),
      LangAuthDashboardInvoicesRoute:
        LangAuthDashboardInvoicesRoute.addChildren({
          LangAuthDashboardInvoicesLayoutRoute:
            LangAuthDashboardInvoicesLayoutRoute.addChildren({
              LangAuthDashboardInvoicesLayoutIndexRoute,
              LangAuthDashboardInvoicesLayoutInvoiceIdRoute,
            }),
        }),
    }),
    LangUnauthRoute: LangUnauthRoute.addChildren({
      LangUnauthLoginRoute,
      LangUnauthIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$lang"
      ]
    },
    "/$lang": {
      "filePath": "$lang",
      "children": [
        "/$lang/_auth",
        "/$lang/_unauth"
      ]
    },
    "/$lang/_auth": {
      "filePath": "$lang/_auth.tsx",
      "parent": "/$lang",
      "children": [
        "/$lang/_auth/another",
        "/$lang/_auth/dashboard/content",
        "/$lang/_auth/dashboard/invoices"
      ]
    },
    "/$lang/_unauth": {
      "filePath": "$lang/_unauth.tsx",
      "parent": "/$lang",
      "children": [
        "/$lang/_unauth/login",
        "/$lang/_unauth/"
      ]
    },
    "/$lang/_auth/another": {
      "filePath": "$lang/_auth/another.tsx",
      "parent": "/$lang/_auth"
    },
    "/$lang/_unauth/login": {
      "filePath": "$lang/_unauth/login.tsx",
      "parent": "/$lang/_unauth"
    },
    "/$lang/_unauth/": {
      "filePath": "$lang/_unauth/index.tsx",
      "parent": "/$lang/_unauth"
    },
    "/$lang/_auth/dashboard/content": {
      "filePath": "$lang/_auth/dashboard/content",
      "parent": "/$lang/_auth",
      "children": [
        "/$lang/_auth/dashboard/content/_layout"
      ]
    },
    "/$lang/_auth/dashboard/content/_layout": {
      "filePath": "$lang/_auth/dashboard/content/_layout.tsx",
      "parent": "/$lang/_auth/dashboard/content",
      "children": [
        "/$lang/_auth/dashboard/content/_layout/comments",
        "/$lang/_auth/dashboard/content/_layout/users",
        "/$lang/_auth/dashboard/content/_layout/",
        "/$lang/_auth/dashboard/content/_layout/posts"
      ]
    },
    "/$lang/_auth/dashboard/invoices": {
      "filePath": "$lang/_auth/dashboard/invoices",
      "parent": "/$lang/_auth",
      "children": [
        "/$lang/_auth/dashboard/invoices/_layout"
      ]
    },
    "/$lang/_auth/dashboard/invoices/_layout": {
      "filePath": "$lang/_auth/dashboard/invoices/_layout.tsx",
      "parent": "/$lang/_auth/dashboard/invoices",
      "children": [
        "/$lang/_auth/dashboard/invoices/_layout/",
        "/$lang/_auth/dashboard/invoices/_layout//$invoiceId"
      ]
    },
    "/$lang/_auth/dashboard/content/_layout/comments": {
      "filePath": "$lang/_auth/dashboard/content/_layout/comments.tsx",
      "parent": "/$lang/_auth/dashboard/content/_layout"
    },
    "/$lang/_auth/dashboard/content/_layout/users": {
      "filePath": "$lang/_auth/dashboard/content/_layout/users.tsx",
      "parent": "/$lang/_auth/dashboard/content/_layout"
    },
    "/$lang/_auth/dashboard/content/_layout/": {
      "filePath": "$lang/_auth/dashboard/content/_layout/index.tsx",
      "parent": "/$lang/_auth/dashboard/content/_layout"
    },
    "/$lang/_auth/dashboard/invoices/_layout/": {
      "filePath": "$lang/_auth/dashboard/invoices/_layout/index.tsx",
      "parent": "/$lang/_auth/dashboard/invoices/_layout"
    },
    "/$lang/_auth/dashboard/content/_layout/posts": {
      "filePath": "$lang/_auth/dashboard/content/_layout/posts",
      "parent": "/$lang/_auth/dashboard/content/_layout",
      "children": [
        "/$lang/_auth/dashboard/content/_layout/posts/_layout",
        "/$lang/_auth/dashboard/content/_layout/posts/"
      ]
    },
    "/$lang/_auth/dashboard/content/_layout/posts/_layout": {
      "filePath": "$lang/_auth/dashboard/content/_layout/posts/_layout.tsx",
      "parent": "/$lang/_auth/dashboard/content/_layout/posts",
      "children": [
        "/$lang/_auth/dashboard/content/_layout/posts/_layout/$postId"
      ]
    },
    "/$lang/_auth/dashboard/invoices/_layout//$invoiceId": {
      "filePath": "$lang/_auth/dashboard/invoices/_layout/_.$invoiceId.tsx",
      "parent": "/$lang/_auth/dashboard/invoices/_layout"
    },
    "/$lang/_auth/dashboard/content/_layout/posts/": {
      "filePath": "$lang/_auth/dashboard/content/_layout/posts/index.tsx",
      "parent": "/$lang/_auth/dashboard/content/_layout/posts"
    },
    "/$lang/_auth/dashboard/content/_layout/posts/_layout/$postId": {
      "filePath": "$lang/_auth/dashboard/content/_layout/posts/_layout.$postId.tsx",
      "parent": "/$lang/_auth/dashboard/content/_layout/posts/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
